package com.cmtc.cms.model;

import com.cmtc.cms.model.enums.ContentStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;


@Entity
@Table(name = "carousel_slides")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CarouselSlide {

	/**
	 * The unique identifier for the carousel slide.
	 * It is the primary key for the 'carousel_slides' table.
	 * The value is automatically generated by the database using an auto-increment strategy.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * The title of the carousel slide, displayed to the user.
	 * This column is required and cannot be null.
	 */
	@Column(name = "title")
	private String title;

	/**
	 * The URL that the user is directed to when they click on the slide.
	 * This column is required and cannot be null.
	 */
	@Column(name = "ref_link")
	private String refLink;

	/**
	 * The URL of the image associated with the carousel slide.
	 * This URL will be used to display the image in the frontend.
	 * This column is required and cannot be null.
	 */
	@Column(name = "image_url", nullable = false)
	private String imageUrl;

	@Enumerated(EnumType.STRING)
	private ContentStatus status;

	/**
	 * User ID of the creator of this slide.
	 */
	@Column(name = "created_by")
	private Long createdBy;

	/**
	 * Timestamp when the slide was created.
	 */
	@Column(name = "created_at")
	private LocalDateTime createdAt;

	/**
	 * User ID of the approver of this slide.
	 */
	@Column(name = "approved_by")
	private Long approvedBy;

	/**
	 * Timestamp when the slide was approved.
	 */
	@Column(name = "approved_at")
	private LocalDateTime approvedAt;

	/**
	 * User ID of the last person who modified this slide.
	 */
	@Column(name = "modified_by")
	private Long modifiedBy;

	/**
	 * User ID of the last person who modified this slide.
	 */
	@Column(name = "modified_at")
	private LocalDateTime modifiedAt;
	
	@Column(name = "to_date")
	private LocalDateTime toDate;
	
	@Column(name = "from_date")
	private LocalDateTime fromDate;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getRefLink() {
		return refLink;
	}

	public void setRefLink(String refLink) {
		this.refLink = refLink;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public ContentStatus getStatus() {
		return status;
	}

	public void setStatus(ContentStatus status) {
		this.status = status;
	}

	public Long getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	public Long getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedBy(Long approvedBy) {
		this.approvedBy = approvedBy;
	}

	public LocalDateTime getApprovedAt() {
		return approvedAt;
	}

	public void setApprovedAt(LocalDateTime approvedAt) {
		this.approvedAt = approvedAt;
	}

	public Long getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public LocalDateTime getModifiedAt() {
		return modifiedAt;
	}

	public void setModifiedAt(LocalDateTime modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

	public LocalDateTime getToDate() {
		return toDate;
	}

	public void setToDate(LocalDateTime toDate) {
		this.toDate = toDate;
	}

	public LocalDateTime getFromDate() {
		return fromDate;
	}

	public void setFromDate(LocalDateTime fromDate) {
		this.fromDate = fromDate;
	}

}
